version: "2"
services:

  grafana:
    image: tomwilkie/grafana:exemplars-1
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
    - "3000:3000"

  db:
    image: grafana/tns-db
    command:
      - '-log.level=debug'
    ports:
      - 0.0.0.0:8000:80
    environment:
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: '6831'
      JAEGER_TAGS: cluster=tns,namespace=tns
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1

  app:
    image: grafana/tns-app
    command:
      - '-log.level=debug'
      - 'http://db'
    links:
      - db
    ports:
      - 0.0.0.0:8001:80
    environment:
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: '6831'
      JAEGER_TAGS: cluster=tns,namespace=tns
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1

  loadgen:
    image: grafana/tns-loadgen
    command:
      - '-log.level=debug'
      - 'http://app'
    links:
      - app
    ports:
      - 0.0.0.0:8002:80
    environment:
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: '6831'
      JAEGER_TAGS: cluster=tns,namespace=tns
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1

  prometheus:
    image: cstyan/prometheus:exemplars-64206a
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    links:
      - app
      - db
      - loadgen
    ports:
      - 0.0.0.0:8003:9090

  jaeger:
    image: jaegertracing/all-in-one:1.17
    ports:
      - "8004:16686"  # tempo
